HOME = "/home/{table}"
SEARCH = "/search/{table}/{from_table}/{foregin_field}/{from_table_field}"
DETAILS = HOME + "/{field}/{value}"
AUTHEFICATE = "/autheficate"
AUTHEFICATION = "/authefication"
EXIT = "/exit"
FORM = HOME + "/form"
FORM_ADD = FORM + "/add"
EDIT = DETAILS + "/edit"
UPDATE = EDIT + "/update"
DELETE = DETAILS + "/delete"
FILE_VIEW = DETAILS + "/{key}/image"
IMAGE_DELETE = FILE_VIEW + "/delete"

DOWNLOAD = DETAILS + "/download"
DOWNLOAD_REDIRECT = DOWNLOAD + "/redirect"
DOWNLOAD_PAGE = DOWNLOAD + "/page"
