"""empty message

Revision ID: bde5c5164439
Revises: c90cf61a5f35
Create Date: 2024-07-10 12:04:13.064303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bde5c5164439'
down_revision: Union[str, None] = 'c90cf61a5f35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status', sa.Enum('Новий', 'В обробці', 'Відправлено', 'Доставлено', 'Відмінено', name='order_status'), nullable=False),
    sa.Column('registered_user', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order')
    # ### end Alembic commands ###
